Paths:
  orig_folder: "F:/ONESELF/AI-preject/vscode-preject/Rect2PPT-picture/shiyongwangye/yuantu"
  mask_folder: "F:/ONESELF/AI-preject/vscode-preject/Rect2PPT-picture/shiyongwangye/mask-file"
  output_folder: "F:/ONESELF/AI-preject/vscode-preject/Rect2PPT-picture/shiyongwangye/output"
  remove-output: "F:/ONESELF/AI-preject/vscode-preject/Rect2PPT-picture/tianjinhuiyi/remove-output"

PPT:
  ppt_path: "F:/ONESELF/AI-preject/vscode-preject/Rect2PPT-picture/shiyongwangye/PPT/其他.pptx"
  slide_layout_index: 6
  left: 1          # 单位英寸
  top: 1           # 单位英寸
  picture_width: 7.5  # 单位英寸
